source 'https://rubygems.org'
ruby '2.1.4'
gem 'sinatra', '~> 1.4', '>= 1.4.7'
require 'sinatra/contrib/all'
require 'tilt/erubis'
gem "passenger", ">= 5.0.25", require: "phusion_passenger/rack_handler"
require 'rubygems'
require 'bundler/setup'
gem 'rspotify', '~> 1.16', '>= 1.16.1'
gem 'pg', '~> 0.18.4'